### ISSUE TITLE
AutoForm.resetForm doesn't set default values

### ISSUE THREAD

**Issue by nkostadinov** [Meteor-Community-Packages/meteor-autoform#1116]
I have a simple schema like this: 

``` javascript
Schemas.Tasks = new SimpleSchema({
    text: {
        type: String,
        label: 'command',
        max: 20
    },
    max_time: {
        type: Number,
        label: 'Max exec time',
        defaultValue: 0
    }
});
```

Whenever I call AutoForm.resetForm(form_id) the form is reset but the field for "max_time" becomes empty instead of its default value of 0. I use autoform to generate the form :

``` javascript
                            {{#autoForm id="editTask" schema=addTaskSchema template="bootstrap3-horizontal" type="method" meteormethod="addTask"}}
                                {{> afQuickFields}}
                                <div class="modal-footer">
                                    <button type="reset" class="btn btn-default cancel" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary save">Save changes</button>
                                </div>
                            {{/autoForm}}
```

Am I doing something wrong ? Why doesnt the field take the default value ?

**Comment by gerwinbrunner** [comment]
+1

**Comment by TimoRuetten** [comment]
+1

Is there still no way to do it in a "AutoForm" way ?

**Comment by soitech** [comment]
`AutoForm._forceResetFormValues(formId);` seems to be working for me.

**Comment by TimoRuetten** [comment]
But this will alos rerender everything. My solution was to build a custom function where I set the values in a form depending on a given object.

**Comment by soitech** [comment]
Sure, you can always write custom functions if you need something different. But _forceResetFormValues is a one line, built in solution to the OP's issue. And it doesn't seem to re-render "everything". It doesn't trigger onRendered of any other templates on the page. The only difference I see between using it and not using it is that after submitting the form, instead of it resetting to an empty form, it resets with default values. Seems like the most "AutoForm" way to do it.

**Comment by nkostadinov** [comment]
@soitech the problem is that the form resets to empty values NOT to default values. 

PS: I've not tested lately if the problem persists.

**Comment by soitech** [comment]
@nkostadinov, yes, the problem still seems to persist, at least in my case. I have some "insert" type forms, that load with a few default values set. After submitting though, they would reset to blank, rather than filling the default  values back in. AutoForm.resetForm() also led to a blank form. However, when I use AutoForm.resetForm() (to clear any validation errors) and THEN use AutoForm._forceResetFormValues(), now after I submit the form, it reloads WITH default values filled in. So if I'm understanding you, that you DO want default values, then AutoForm._forceResetFormValues(formId) should work for you.

**Comment by TimoRuetten** [comment]
I also used forceResetFormValues before instead but the problem for me was that this method will remove the fields from DOM and rerender it to DOM - you see this when you redoing this a few times (sometimes it will be this fast so you can not see it - but mostly you will see this "jump" in the structure of your website) - because of this disadvantage I preferred the custom function.
