### ISSUE TITLE
Auto-fill form with data from a collection

### ISSUE THREAD

**Issue by dlodeprojuicer** [Meteor-Community-Packages/meteor-autoform#1153]
I am trying to update data same as [this example](http://autoform.meteor.com/updateaf), but instead of using `afQuickField name="nameOfTheField` I am using `afQuickFields`. I tried displaying fields individually it does not work either. Browser logs show the correct data. 

**_HTML**_
![customer1](https://cloud.githubusercontent.com/assets/2291356/9435597/78582594-4a49-11e5-87d7-5f8b810cb3b5.JPG)

**_JS**_
![customer3](https://cloud.githubusercontent.com/assets/2291356/9435638/b554fef4-4a49-11e5-9a32-3cfa0a61b99c.JPG)

Trying the same using field name and value attribute works, but approach is too specific and is not ideal in my case
![customer1](https://cloud.githubusercontent.com/assets/2291356/9435680/f9bf6ebc-4a49-11e5-93cb-b324bcd1088f.JPG)

**Comment by abecks** [comment]
Is your helper not working because the template is named ```customerUpdate``` but in your JS it is referred to as ```updateCustomer``` ?

The concept of returning the data in a Session variable seems OK, but I would rather store just the ID in the Session variable and do the findOne call in the helper instead of the event handler:

```js
Template.updateCustomer.events({
   'click #FormId': function(evt){
        Session.set('customerUpdateInstance', 'shjkh23897x');
    }
});

Template.updateCustomer.helpers({
    instanceData: function(){
        return pptForm.findOne( Session.get('customerUpdateInstance') );
    }
});
```

I don't like the idea of storing large ambiguous objects directly in the Session.

**Comment by Simomultimedia** [comment]
Hi @abecks. Helper name is was typo. I see the concern regarding large objects, I will try to stick to IDs from now on thanks for the tip.
