### ISSUE TITLE
Alternative ways to set autoform-hooks.

### ISSUE THREAD

**Issue by macrozone** [Meteor-Community-Packages/meteor-autoform#1314]
I think we need an other way to define autoform hooks than the global hooks.

They are hard to use when your form may occure multiple times on same page because they rely on dom-ids (and i would try to get rid of them). Its also difficult to e.g. append more data from the template context before submitting or calling a method.

You also usually end up creating a hook for one specific form. Not beeing able to define this in the template itself feels unintuitive.

A solution would be to be able to pass the hook object to the autoform/quickform instance in a helper

`{{>quickForm hooks=myHooks collection="MyCollection" type="insert" }}`

```
Template.myTemplate.helpers({
  myHooks() {
    return {
       onSuccess(result){
       ...
       },
       after: {
           insert(error, result) {
          }
       }
    }
  }
});`
```

Another way would be to use events:

```
Template.myTemplate.events({
['onsuccess.autoform'](result) {

},
['after.insert.autoform'](error, result) {

}

});
```

The version with the helper sort of works already. You can do something like the following:

```
AutoForm.addHooks(null, {
    onSuccess(formType, result){
        if(this.formAttributes.onSuccess) {
            this.formAttributes.onSuccess.call(this, formType, result);
        }
    }
});

`{{>quickForm onSuccess=onSuccess collection="MyCollection" type="insert" }}`

Template.myTemplate.helpers({
  onSuccess() {
    return function(formType, result) {
       ....
    }
  }
});
```

what you guys think?

**Comment by aldeed** [comment]
Events aren't really an option because in general hooks need to be able to return values or otherwise impact the submission/rendering process. Helpers are probably the way to go, but yeah in general this is something I'm thinking about for future release.

One reason why this is not straightforward, and why `id` is currently necessary and might always be, is because I've been working toward decoupling submission from generation. I am (slowly) trying to get to a point where you could use an autoform-submission pkg without an autoform-generation package, and autoform-submission will ideally not be dependent on Blaze, and could be used with React, with your own components, or even with static HTML. So in that world, submission hooks need to be assigned by form ID, or possibly by any jquery selector, or attached to the form element.
