### ISSUE TITLE
boolean-checkbox with Inspinia - no response

### ISSUE THREAD

**Issue by ouya99** [Meteor-Community-Packages/meteor-autoform#1373]
I have a normal boolean field inside addresses schema

  "addresses.$.main": {   
    type: Boolean,
    optional: true,
    autoform: {
      type: "boolean-checkbox"
    }
  }

Using it with 

{{> afQuickField placeholder="addresses" label="addresses" name="addresses"}}

will display the checkbox and the label, but the box itself cannot be checked or unchecked. No UI response at all.

How can that be? Trying same code with "boolean-select" as type works fine.

**Comment by java99** [comment]
I am using it with the Inspinia templates. Could this be a problem?

**Comment by teban1812** [comment]
Same behavior here using Inspinia template

**Comment by java99** [comment]
type: Boolean,
    optional: true,
    autoform: {
      template: "plain",
      label: false,
      afFieldInput: {
         type: "boolean-checkbox",
         class: 'i-checks',
       }
     }

Template.createContact.rendered = function(){

    // Initialize i-check plugin
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
    });

};

solved it. Yet somehow the form does not save the content anymore.. have to investigate more.

**Comment by artjomg** [comment]
@java99 
Here is my investigation on inspina checkboxes so far:
When using the autoform plugin the checkboxes and radio boxes are rendered by default with the css file from this plugin: https://github.com/flatlogic/awesome-bootstrap-checkbox

![screenshot 29](https://cloud.githubusercontent.com/assets/7611016/13906608/f3c15d6e-eeda-11e5-8fbd-579377c6528f.jpg)

The issues with this css based solution is that the nested elements of the label are expected in the certain order, which is different.

Assuming a field:

```
distribute:{
    type: Boolean,
    optional: true,
    label: "Distribution",
    autoform: {
      type: "boolean-checkbox"
    }
  }
```
results in the following dom structure:

```
<div class="form-group">
   <label class="col-sm-3 control-label" for="xMELrQGQPsgFHqAer"></label> 
    <div class="col-sm-9">
     <div class="checkbox">
    <label>
      <input type="checkbox" value="true" name="distribute" id="xMELrQGQPsgFHqAer" data-schema-key="distribute">
      Distribution
    </label>
  </div>
      <span class="help-block"></span>
    </div>
  </div>
```
The issue here is that the checkbox is surrounded by another label attribute where the css classes of the bootstrap-awesome-checkbook stop working.

Looking closer at insignia examples: http://localhost:3000/formBasic
![screenshot 30](https://cloud.githubusercontent.com/assets/7611016/13906655/418c1fce-eedc-11e5-9dec-830e0b331f81.jpg)
```
                                    <div class="checkbox">
                                        <input type="checkbox" id="checkbox1">
                                        <label for="checkbox1">
                                            Check me out
                                        </label>
                                    </div>
```
This is the expected structure for the css classes, which differs from one above.
What I did as quick workaround is a custom inputType:

![screenshot 31](https://cloud.githubusercontent.com/assets/7611016/13906701/9a673042-eedd-11e5-8c39-fa5fb7c707b5.jpg)

```
AutoForm.addInputType("boolean-checkbox-custom", {
  template: "afCheckboxCustom",
  valueOut: function () {
    return !!this.is(":checked");
  },
  valueConverters: {
    "string": AutoForm.valueConverters.booleanToString,
    "stringArray": AutoForm.valueConverters.booleanToStringArray,
    "number": AutoForm.valueConverters.booleanToNumber,
    "numberArray": AutoForm.valueConverters.booleanToNumberArray
  },
  contextAdjust: function (context) {
    if (context.value === true) {
      context.atts.checked = "";
    }
    //don't add required attribute to checkboxes because some browsers assume that to mean that it must be checked, which is not what we mean by "required"
    delete context.atts.required;
    return context;
  }
});

```

```
<template name="afCheckboxCustom">
  <div class="checkbox">
      <input type="checkbox" value="true" {{atts}} />
      <label>{{afFieldLabelText name=this.name}}</label>
   </div>
</template>
```

And the reference in the schema field:

```
  distribute:{
    type: Boolean,
    optional: true,
    label: "Distribution",
    autoform: {
      type: "boolean-checkbox-custom"
    }
  }
```

![screenshot 32](https://cloud.githubusercontent.com/assets/7611016/13906771/00f9c904-eedf-11e5-97fa-3a1e83ecf960.jpg)

The marked area and the checkbox are now working and functional.
However the label after the checkbox is not working since it is missing the <label for="... directive.
 
Adding it manually through inspector in Chrome makes it functional. But the template could simply skip this second label.

```
<div class="form-group">
    <label class="col-sm-3 control-label" for="uXZwMezmTWpLTC5Kz">Distribution</label>
    <div class="col-sm-9"> 
    <div class="checkbox">
      <input type="checkbox" value="true" name="distribute" id="uXZwMezmTWpLTC5Kz" data-schema-key="distribute">
      <label for="uXZwMezmTWpLTC5Kz">Distribution</label>
   </div>
      <span class="help-block"></span>
    </div>
  </div>
```

All in all a working workaround. But I don't know how to add the "for" directive to the label.
Same has to be done with radios.
An alternative might be a fix of css classes or removal of this plugin.

**Comment by iamrommel** [comment]
This works great.. Thanks @artjomg for the invistigation

**Comment by mwaschkowski** [comment]
Wow, simply fantastic. I had the same issue and spent a couple of hours trying to work things out and then I tried your solution and it worked the first time. Amazing! Thank you very much!
