### ISSUE TITLE
problem with autoValue

### ISSUE THREAD

**Issue by rslp2** [Meteor-Community-Packages/meteor-autoform#1411]
I'm trying to set **Meteor.userId()** as default value for a field in my simpleSchema.

here is the schema:

```
AdsSchema = new SimpleSchema({
  title: {
    type: String,
    label: "Title"
  },
  insertedBy: {
    type: String,
    label: "Inserted By",
    autoform:{
      type:"hidden"
    },
    autoValue: function() {
      if (Meteor.userId()) {
        return Meteor.userId();
      }
    }
  }
})
```

autoForm:

`{{> quickForm schema= "AdsSchema" collection="Ads" id="insBaseAds" type="insert"}}`

but after inserting by above autoform, the inserted document on MongoDB is:

```
{
    "_id" : "Zm5TML5bwJhyN8B9F",
    "title" : "test"
}
```

it means "insertedBy" field has never filled!

how can I fix this?

**Comment by acomito** [comment]
I use this:


```
    createdBy: {
        type: String,
        autoValue: function() {
                if (this.isInsert && (!this.isSet || this.value.length === 0)) {
                    return Meteor.userId();
                }
        }
    },
```
`(this.isInsert && (!this.isSet || this.value.length === 0)) ` ensures that it is only applied during an insert. Otherwise, it'll calculate a new value on every update (and at other odd times too). For instance, if I changed a field on the document as an admin, it would update createdBy with the admin's userId... which is not what I wanted.
