### ISSUE TITLE
Item label not honored in array field

### ISSUE THREAD

**Issue by diegonc** [Meteor-Community-Packages/meteor-autoform#1491]
When a schema has an array field and you try to define a label for each item in the array, what it actually gets displayed is the label of the parent array field.

For an example look at the quickform playground [here](http://autoform.meteorapp.com/quickform) and give it the following JSON.

```
{
   items: {
      label: "Custom Label",
      type: Array
   },
   "items.$": {
      label: "Custom Item Label",
      type: Object
   },
   "items.$.name": {
      type: String
   },
   "items.$.quantity": {
      type: Number
   }
}
```

You can see the text "Custom Label" for both the array field and its items.

![..](http://i.imgur.com/uYJaOYL.png)

I'm actually trying to hide it altogether by setting it to a falsy value and making the with template [here](https://github.com/aldeed/meteor-autoform/blob/devel/templates/bootstrap3/components/afObjectField/afObjectField.html#L3) fail its test. But it doesn't accept strings either.

**Comment by cunneen** [comment]
I also have this issue.

**Comment by Roshdy** [comment]
My solution was to modify the bootstrap template on autoform 
/packages/meteor-autoform-devel/templates/bootstrap3/components/afArrayField

of course "packages" directory is under the root of meteor (local copy)

Since meteor looks for local packages according to the package name, if it couldn't find one, it downloads it from the internet.

Another advice, to have a stable production environment, always copy ALL the packages you use locally, not to be vulnerable to any updates or file replacements of the package.
