### ISSUE TITLE
Support Nested Forms

### ISSUE THREAD

**Issue by aldeed** [Meteor-Community-Packages/meteor-autoform#332]
Many places in the code where we select based on `[data-schema-key]` in the template will need to be changed to ignore sub-forms. PR #330 fixed one area but there are several more, and it will need to be tested well in general before we can claim to support it. Technically we should probably look at the `form` attribute as well in case an input is linked to a separate form.

**Comment by fusepilot** [comment]
I ran into the infinite loop problem today with a nested form. After poking around I was able to make it stop by commenting out this [line in autoForm.js](https://github.com/aldeed/meteor-autoform/blob/8d22ba01449ea8f56e44e23c91fc33df193eff63/components/autoForm/autoForm.js#L131). Obviously this breaks other stuff, but thought it might help pinpoint.

**Comment by aramk** [comment]
@fusepilot I believe I fixed this without causing issues in [this commit](https://github.com/aramk/meteor-autoform/commit/a63ccfc6997a6bc2a1a6e6850d687bf12ac1f02c). The [feature/subforms](https://github.com/aramk/meteor-autoform/tree/feature/subforms) branch in my repo pretty much works, but I haven't had a chance to merge it in yet. The only issue as I mentioned earlier is that calling `AutoForm.resetForm()` clears the contents of the subform fields. Otherwise I'm using it as a custom package in my `packages` directory and it appears to work well.

**Comment by fusepilot** [comment]
Thanks @aramk, that branch does indeed seem to fix it. Looking forward to the merge.

**Comment by aramk** [comment]
I'll make a PR in any case and we can work from there.

**Comment by aldeed** [comment]
A lot of internals have changed in `devel` branch and are still changing, so some of this PR will have to be redone. I suspect that there are still issues anyway. If anyone has an example of a case where subforms would be needed, that would be helpful for testing. I've never had any use for subforms.

**Comment by aramk** [comment]
Thanks for the heads up. In my case I had a customer form with a set of order schedules containing an order template which is used to populate new orders in the schedule. I'm reusing a single order form for both these instances and the template, such that any number of them can appear on a customer's page. While some of it could be handled with sub-schemas, the order form has its own complex logic.

**Comment by rclai** [comment]
Isn't subforums technically not allowed in html?

http://stackoverflow.com/questions/379610/can-you-nest-html-forms

**Comment by aramk** [comment]
See the next two answers, it mentions it’s possible. We’re not going to let something like standards stop us from doing what we want :P
