### ISSUE TITLE
Find a way to get actual invalid value entered in type=date field in Chrome

### ISSUE THREAD

**Issue by comerc** [Meteor-Community-Packages/meteor-autoform#610]
http://autoform.meteor.com/types

Input type: date 
Schema type: Date

Type: 30.04.2000
Console:
`Submitted value: Sun Apr 30 2000 04:00:00 GMT+0400 (MSD)`

Type: 31.04.2000
Console: 
`Submitted value: undefined`

**Comment by aldeed** [comment]
I can look into it, but I think this is just the way the browser does it. There's probably no way for autoform to know that a value was entered.

**Comment by comerc** [comment]
It looks bad from the point of view of the user: I typed value (the browser allows but not allows you to enter 32, for example), and I see "field required".

**Comment by aldeed** [comment]
Which browser are you using?

See http://codepen.io/anon/pen/bNgawN?editors=101

In Chrome, which is the only browser that supports date inputs, it returns an empty string for the value if you set it to anything other than a valid date.

The other browsers render a normal "text" input for dates because they don't yet support type="date". If you're using one of those and autoform is stripping out the invalid dates, then maybe that is something that could be fixed.

**Comment by comerc** [comment]
Chrome, of course.
One interesting point: I see change-event only if valid value, but I see keyup-event for any case.  

I found, try:
`console.log(event.target.checkValidity());`
or
`console.log(event.target.validity.badInput);`

**Comment by aldeed** [comment]
That's interesting, but looking at the validity object and the element object, I still don't see any way to get the actual value that was entered (the invalid value). It seems like there must be some way to get it, but all the value properties are set to an empty string when it's invalid.

If we can't get the string they entered, I don't think we can show the correct error message.
