### ISSUE TITLE
Add ability to reorder afArrayFields

### ISSUE THREAD

**Issue by fusepilot** [Meteor-Community-Packages/meteor-autoform#624]
I'm trying modify the order of items inside of a field array while keeping their respective values. Utlimately, the goal is to create a drag and drop interface that would wrap this functionallity. This is what I've got so far:

```
ArrayTracker.prototype.swapByIndex = function atSwapByIndex(formId, field, indexA, indexB) {
  var self = this;
  self.ensureField(formId, field);

  //get current field array
  var fieldArray = formData[formId].mDoc.getValueForKey(field);

  //swap array values  
  var swap = fieldArray[indexA];
  fieldArray[indexA] = fieldArray[indexB];
  fieldArray[indexB] = swap;

  //set new field array
  formData[formId].mDoc.setValueForKey(field, fieldArray);

  //reset form to reflect new order
  AutoForm.resetForm(formId);
}
```

But `resetForm` is a brute force way to apply the new state to the form and loses anything else that was modifed in the form. I've tried modifing the `self.info[formId][field].array` to reflect the new indices and then calling `self.info[formId][field].deps.changed()`, but state is never changed.

How would you go about this @aldeed?

**Comment by aldeed** [comment]
Some of this stuff is changing in devel branch/5.0. I'll investigate the best way to do this when a bit closer to releasing that.

**Comment by fusepilot** [comment]
Sounds great. Thanks!

**Comment by aldeed** [comment]
I haven't looked into this really deeply, but enough to see that it will be tricky. The main problem is update forms, where there is a lot of logic around making sure that we're correctly tracking which items you remove so that the correct array indices get removed from the doc.

Short answer is that the best approach will probably be to

1. Call `removeFromFieldAtIndex` for the dragged element.
2. Make a variation of `addOneToField` that inserts into the array at a particular index, and then set those values.

We could also revisit the way it tracks overall, but I know that was a mess to get working in the first place. If we're only ever replacing the entire array, it could be simpler, but I don't recall the use cases for why it is the way it is.

**Comment by rikonor** [comment]
Please review #1370 for how I dealt with reordering arrays.

**Comment by cloudrocketsoftware** [comment]
Is this implemented already? How can I use the solution @rikonor created?

**Comment by rikonor** [comment]
@cloudrocketsoftware My PR was never merged.
Considering the original repo has almost not changed at all since my fork happened, you'd probably be fine using the fork.
That said, you'd be better off doing your own fork and applying my changes there.
