### ISSUE TITLE
Question/Feature Request: Errors From Custom Input Types

### ISSUE THREAD

**Issue by Gaelan** [Meteor-Community-Packages/meteor-autoform#634]
# Context

I have a custom field which is displayed in the text box as a URL on a remote site (similar from the app's perspective to YouTube), but internally stores it as the remote object's ID. The ID is then used to generate embed code.
# Problem and Current Solution

I (obviously) need to handle invalid URLs. The way I currently do this is by returning `-1` (not a valid ID) as the ID from the `valueOut` function, then use a custom validation handler at the Simple Schema level to produce a nice error message. The system works fine, but…
# Question

I'm wondering if there is/will be/should be a way to directly generate a validation error from the `valueOut` function.

**Comment by aldeed** [comment]
The `valueOut` function would not be the correct place for it because it will need to be part of the validation process, which happens independently of getting values, and does not necessarily need to happen every time a value is retrieved.

A better idea would be to support an optional property in the input type definition, `inputValidate` or something similar, which can be called whenever autoform validates and done in such a way that the errors will not be accidentally overwritten.

**Comment by arvi** [comment]
Hi again! I was just wondering if you can provide any suggestions to solve this custom date input problem I'm having using autoform-pickadate. 

https://github.com/RobertLowe/autoform-pickadate/issues/1

I have not received a reply from the author, so I'm thinking maybe you have an idea. :) Thanks for your help!

**Comment by tcastelli** [comment]
+1 trying to do the same and thought about using contextAdjust for that, but seems pretty complicated for something quite simple
