### ISSUE TITLE
default value for 'hidden field'

### ISSUE THREAD

**Issue by kamil7732** [Meteor-Community-Packages/meteor-autoform#743]
Hi,
I stumbled upon such issue: 

```
{{#autoForm collection="OrderStatus" id="insertOrderStatusForm" type="insert"}}
                                    <fieldset>
                                        <button type="submit" class="btn btn-primary">Dodaj</button>
                                        {{> afQuickField name='status'}}
                                        {{> afQuickField name='reminder'}}
                                        {{> afQuickField name="additionalPL" rows=6}}
                                        {{> afQuickField name='additionalEN' rows=6}}
                                        <div style="visibility: hidden">
                                            {{> afQuickField name='order' value=currentOrderId}}
                                        </div>


                                    </fieldset>

                                {{/autoForm}}
```

where currentOrderId is a helper. Eveything works fine...for first time. If I try to batch insert things (reuse form after first submit) then I get exception "message: "Order is required"}" so it's like the value wasn't used from helper after first submition. I will try to go through doc way of pushing default values.

**Comment by aldeed** [comment]
Not sure, but I doubt the visibility has anything to do with it. Please see if this is fixed when using autoform 5.0, now released. If not, provide a simple reproduction app showing the issue.

**Comment by lucatros** [comment]
Having the same problem here. I suspect Autoform clears all the fields after the template is rendered and the form type is "insert" so if you set a custom value, it will end up empty.

**Comment by joerodrig3** [comment]
I have the same issue as well. My autoform looks like:
```
{{#autoForm schema=UISchemas.Resource id="resourceCreationForm" type="method" meteormethod="createResource" }}
                            <fieldset>
                                {{> afFormGroup class="course-id" name='crs_id' value=activeCourseID}}
                                {{> afFormGroup name='name'}}
                                {{> afFormGroup name='description'}}
                                {{> afFormGroup name='location'}}
                                {{> afFormGroup name='due_date'}}
                            </fieldset>
                            <button type="submit" class="btn btn-sm btn-success"><i
                                    class="fa fa-plus"></i>
                                Add Resource
                            </button>
                        {{/autoForm}}
```

Typically, I'd want to hide the "course-id" input because it is reactive. On form submission, this input is cleared and not repopulated, causing the issue noted above.
 
I've tried disabling  auto clear on submission and added a "reset" button that manually removes each input value that i'd like to have cleared:
```
 'click .clear-assn-form' : function(){
        var parentDivs    = $('fieldset.clearable-inputs').children('div'),
            inputsToClear = $(parentDivs).children(':input');

        //Clear each of the inputs
        inputsToClear.each(function(){
            $(this).val('');
        });
    }
```
Unfortunately this isn't the most ideal workaround because doing so results in each cleared input to display an error message to the user

**Comment by joerodrig3** [comment]
I was able to reproduce the issue in the meteorpad playground here:
http://meteorpad.com/pad/pisDQd8F8eLExAdvi/autoform_repopulate_bug

**Comment by joerodrig3** [comment]
My permanent solution was to use an<a href="https://github.com/aldeed/meteor-autoform#callbackshooks"> Autoform "before" hook </a>to pass values without inserting them directly into the form. The hidden value is now stored in a session variable and is referred to in the before hook. I believe this may resolve the original posters issue as well.

```
//hooks.js
var addCourseIDHook = {
    before: {
        method: function(doc){
            doc.courseID = Session.get("activeCourseID");
            return doc;
        }
    }
};

AutoForm.addHooks(['tagsetCreationForm'],addCourseIDHook);
```

**Comment by joerodrig3** [comment]
I've since found a better way to fix this issue: You can write a helper that retrieves your document data and set the data context using the <a href="https://github.com/aldeed/meteor-autoform#a-basic-update-form">doc attribute</a>

Any data set in the form through the doc attribute maintains its value state even after submission(without setting resetOnSuccess equal to false).

For a clearer explanation, please also reference <a href="https://github.com/aldeed/meteor-autoform/issues/1027">issue 1027</a>

**Comment by JulianKingman** [comment]
Thanks for the tip @joerodrig3
