### ISSUE TITLE
"unresponsive script" warning / performance of larger forms

### ISSUE THREAD

**Issue by nate331** [Meteor-Community-Packages/meteor-autoform#795]
My form contains an array field. Each array item is a subobject with about 5 fields. When the array has only a few entries everything is working fine. But if the number of array items increases the page gets slower (if there are more than 10 array items, clicking on the "plus" symbol to add an item already takes 1-2sec). The submitting also takes a long time. With 15 array items it takes more than 30s (and takes all CPU during that time). The main problem is that the browser raises an "unresponsive script" warning asking the user to stop the script (which kills meteor). But an array with 15 items is a pretty common usecase. 

With autoform 5 the performance increased by about 60-70% but it still takes 15s on bigger forms. So there is always the danger of the "unresponsive script" error.

Are there ways to increase the performance of autoform? (maybe making some features not responsive? making validation not responsive?) How could the Browser Warning be avoided?

**Comment by aldeed** [comment]
There was another report of this. Have you tried yet with Meteor 1.0.4.1? I think I saw something in the release notes about performance improvements for array iteration. Could be some autoform issue aggravating it, too. I'll look into it when I have some time.

**Comment by nate331** [comment]
I tried with autoform 4 and Meteor 1.0.4. This did not make the rendering any faster. And the submitting took about 25% longer than with Meteor 1.0.3.
I could not try autoform 5 and Meteor 1.0.4 yet because of issue 790.

**Comment by aldeed** [comment]
It would really help to have a repo I can clone with a reproduction of this issue.

**Comment by nate331** [comment]
Here is a reproduction: https://github.com/nate331/arrayfieldPerformanceReproduction

If you add 10 array items it will take a long time to save.
I was trying the same thing with the books schema as array item schema. Then it took a lot less time. It seems like my custom validation functions might be responsible for the long submitting time, but not sure. 
In the console it is also showing a lot of "duplicate _id" prints. Maybe that's refers to a problem as well.

**Comment by abecks** [comment]
I have noticed this aswell, with a very similar use case to @nate331 with an array of objects.

The performance of afArrayField is terrible. I spent the better part of the afternoon debugging why, and it seems to me that there are a number of contributing factors. Most of it is seems to be because of the reactivity.

Here is what I've found:

Adding or removing array items, or changing field values inside the array invalidates the computations for every single field in the entire form. The call to ```self.info[formId][field].deps.changed();``` inside ```ArrayTracker.prototype.addOneToField``` seems to be the root cause when adding a new array item. It appears to eventually invalidate one of the reactive dependencies of ```afFieldInputContext``` for every single field present in the form. That function then runs ```updateTrackedFieldValue``` for every single field, which invalidates the dependencies for every single field in the form (including ```AutoForm.getFieldValue```, which makes it unusable for arrays). I haven't been able to debug Blaze to figure out why. The more fields in the form (or array), the longer this will take to process and it takes a ridiculous amount of time.

@aldeed Do you have any idea where I might start to debug this further? I'd like to help make this more performant if I can.

**Comment by abecks** [comment]
I should also note that the timeout on ```markChanged``` exasperates the problem, causing any ```AutoForm.getFieldValue``` computations to run several times.

**Comment by fuatsengul** [comment]
+1 to the list :(
I'm rendering a dynamic table of dropdown items, 180 items takes around 30 seconds and freezing the browser.

**Comment by markdowney** [comment]
Same issue here. Any suggestion to workaround this?

**Comment by abecks** [comment]
Render the fields yourself in an each loop. Avoid afArrayField. You can
still use quickField

**Comment by DanielDornhardt** [comment]
Hi, we're having this issue massively right now, with autoform arrays nested 3 levels deep in some cases.

It's crazy how fast it gets to become really really slow really really quickly when adding to the form, it seems to be becoming exponentially slower, not linearly. This is really biting us at the moment because we're on a very tight deadline at the moment and destructuring these forms definitely would take some time...

If anybody has an idea for a patch to autoform to speed this up, event if it'd have some other tradeoffs maybe, i'd be very interested.

**Comment by abecks** [comment]
My only solution was to completely avoid using afArrayField. I've poured over the code for the array field and its very difficult to figure out due to an insane amount of nested reactivity. 

You can still do forms with array-like fields, but you need to build that component yourself. You can either create a custom AutoForm input type (which is what I do now), or render the array items yourself and patch them into the submitted form document via the formToDoc hook. The former method being preferred because it allows you to maintain automatic validation.

Read more about creating custom input types: https://github.com/aldeed/meteor-autoform#defining-custom-input-types

You can create your own array field component and you can even continue to use validation on array-nested object properties via afFieldMessage.

**Comment by DanielDornhardt** [comment]
Hi @abecks, thank you for the hints. I'll see how we can solve this properly, probably by decomposing our big-a** form / document into multiple collections and creating separate interfaces for some parts of it.
