### ISSUE TITLE
AutoForm.getFieldValue('someField') does not rerun reactively upon keyUp

### ISSUE THREAD

**Issue by koszta** [Meteor-Community-Packages/meteor-autoform#823]
`AutoForm.getFieldValue('someField')` does not rerun reactively upon keyUp, only upon blur, but when I call it manually it returns the current updated value.

**Comment by mattkrick** [comment]
I had this same problem & I think it's due to the `_.throttle()`. Through a bunch of `console.log`s, I found out if you change a value very quickly, it updates, or very slowly (I assume slower than 300ms) it updates. But somewhere in the middle it doesn't register.

As a workaround (my problem was with a timepicker popover) I blur the field manually.

**Comment by aldeed** [comment]
It's not currently expected to run on keyup, only on change/blur. But it might make sense to have it run on keyup, too. Will have to decide whether running on keyup should be optional.

**Comment by j3omal** [comment]
+1 - I would use the keyup functionality, if added. 

Thanks for these great packages!

**Comment by VladShcherbin** [comment]
The keyup event is a must. That way, we can pass the value to markdown block and see the result. Please, add this feature.

**Comment by patrickdevivo** [comment]
+1 would love to see this available as well
