### ISSUE TITLE
Fieldset Support

### ISSUE THREAD

**Issue by SachaG** [Meteor-Community-Packages/meteor-autoform#860]
So far I've used my own AutoForm template in Telescope to add fieldsets that let me group fields together inside a single Quickform. 

But having my own template with its own custom logic isn't really maintainable, so I'd like to try and submit a PR to add fieldsets to AutoForm core, if that's a feature that makes sense.

Any tips on where I should start?

**Comment by SachaG** [comment]
So I looked into modifying the `afQuickFields` template, but I'm not quite sure how to do it because it doesn't seem like this template has the fields as its data context like I thought it would. So I'm not entirely sure where the field data is coming from, and how to iterate over it to extract the fieldsets…

**Comment by aldeed** [comment]
The [afFieldNames helper](https://github.com/aldeed/meteor-autoform/blob/master/autoform-helpers.js#L119) has most of the magic logic. It returns a list of field names based on a number of factors. If `name` is set, then the fields are limited to fields at and below that field name in the tree. Otherwise all fields in the schema. But then `fields` and `omitFields` attributes are also checked, further limiting that list.

I'm not sure how easy it will be to add your logic there, so it might have to be done at a higher level. Maybe the `quickForm` template can check for fieldsets and call `afQuickFields` multiple times, once for each fieldset, passing in the fieldset name as yet another limiter that `afFieldNames` will respect.

**Comment by SachaG** [comment]
Yes, that's the approach I was going for with `afQuickFields`:

```html
<template name="afQuickFields">

  <div class='no-fieldset'>
    {{#each afFieldNames name=this.name}}
      {{log}}
      {{> afQuickField quickFieldAtts}}
    {{/each}}
  </div>
  
  {{#each afFieldsets}}
      {{log}}
      <fieldset>
        <h3 class="af-fieldset-heading">{{this.fieldsetName}}</h3>
        {{#each afFieldNames name=this.name fields=fieldsForFieldset}}
          {{log}}
          {{> afQuickField quickFieldAtts}}
        {{/each}}
      </fieldset>
  {{/each}}

</template>
```

But I got stuck when trying to generate `afFieldsets` and `fieldsForFieldset`, since I wasn't sure how to access the current schema. Maybe we could Skype about it sometime?

**Comment by SachaG** [comment]
OK, I'm making some progress. Not very far now :)
