### ISSUE TITLE
Skipping validation?

### ISSUE THREAD

**Issue by ntoka** [Meteor-Community-Packages/meteor-autoform#881]
Hi,
I am using insert autoform for collection "Posts" and I need to skip validation before saving when "Save Draft" button is pressed and validate form before submitting when "Add post" button is pressed. Is there a functionality for this? I tried adding validation="none" attribute and then manually validating fields but that did not do the trick.

**Comment by aldeed** [comment]
There is no way to skip validation entirely from the client if you did `attachSchema` on the collection. (Otherwise that would be a security hole.) So you'll have to remove the `type` from the form, add an `onSubmit` hook, and based on your logic, either call `insert` on the client (which will validate), or call a server method that will do the insert without validation (pass `{validate: false}` as the second argument of your `insert` call in the server method).

**Comment by TechplexEngineer** [comment]
What about if I want disable validation for debugging to test my server-side validation logic?
